### ISSUE TITLE
homepage link is broken

### ISSUE THREAD

**Issue by victornpb** [prantlf/rollup-plugin-shebang-bin#1]
if you try to follow the link in the package it 404s
<img width="703" alt="image" src="https://user-images.githubusercontent.com/3372598/171783827-ac05671f-7158-424c-9a07-7ca95a964809.png">

**Comment by prantlf** [comment]
Oh, you're right. Must've been some copy&paste. Thanks for reporting it!

Fixed in [0.0.4](https://github.com/prantlf/rollup-plugin-shebang-bin/releases/tag/v0.0.4).
